[package]
	authors = ["Thomas BESSOU <thomas.bessou@hotmail.fr>"]
	description = "An idiomatic implementation of serde/avro (de)serialization"
	edition = "2021"
	license = "LGPL-3.0-only"
	name = "serde_avro_fast"
	repository = "https://github.com/Ten0/serde_avro_fast"
	version = "0.1.0"

[features]
	snappy = ["snap", "crc32fast"]

[dependencies]
	apache-avro = { git = "https://github.com/apache/avro.git" }
	crc32fast = { version = "1", optional = true }
	digest = "0.10"
	flate2 = "1"
	integer-encoding = { default-features = false, version = "3" }
	rust_decimal = { version = "1", default-features = false, features = ["std", "serde-with-str"] }
	serde = "1"
	serde_derive = "1"
	serde_serializer_quick_unsupported = "0.1"
	snap = { version = "1", optional = true }
	thiserror = "1"

[dev-dependencies]
	anyhow = "1"
	criterion = "0.4"
	lazy_static = "1"
	paste = "1"
	pretty_assertions = "1"
	serde_bytes = "0.11"
	serde_json = "1"

[[bench]]
	harness = false
	name = "single"
