[package]
	authors = ["Thomas BESSOU <thomas.bessou@hotmail.fr>"]
	description = "An idiomatic implementation of serde/avro (de)serialization"
	edition = "2021"
	license = "LGPL-3.0-only"
	name = "serde_avro_fast"
	version = "0.1.0"

[dependencies]
	apache-avro = { git = "https://github.com/apache/avro.git" }
	integer-encoding = { default-features = false, version = "3" }
	serde = "1"
	thiserror = "1"

[dev-dependencies]
	lazy_static = "1"
	paste = "1"
	pretty_assertions = "1"
	serde_bytes = "0.11"
	serde_json = "1"
	static-cond = "0.3"
